version: '3.8'
services:
  todo-client:
    image: todo-client
    build: ./client
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - todo-network
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
  todo-server:
    image: todo-server
    env_file: ./server/dev.env
    build: ./server
    ports:
      - '5000:5000'
    networks:
      - todo-network
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - todo-db
  todo-db:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - todo-network
networks:
  todo-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local
